server:
  port: 8081

my:
  kafka:
    topic: test
    bootstrap:
      servers:
        config: localhost:9092
    security:
      protocol: SASL_PLAINTEXT
    sasl:
      mechanism: PLAIN
      jaas:
        config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="producer" password="producer-secret";'

