# datasource config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  # spring data jpa config
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

